# Generated by Django 6.1.1 on 2026-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blinkit',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('Productname', models.CharField(max_length=10)),
                ('Mobile_Number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
